name: myenv
dependencies:
  - python=3.8
  - pip:
    - tensorflow==2.8
    - tifffile==2021.7.2
    - scikit-image==0.19.2
    - numpy==1.23.5
    - scipy==1.9.1
    - pandas==1.4.4
    - ipykernel==6.15.2
    - matplotlib==3.5.2
channels:
  - conda-forge
